version: "3"

services: 
  product-service:
    build: ./product
    volumes: 
      - ./product:/usr/src/app
    ports: 
      - 5001:8080

  website:
    build: ./website
    volumes: 
      - ./website:/var/www/html
    ports: 
     - 5000:80
    depends_on: 
      - product-service
